#!/usr/bin/perl
use warnings;
use strict;

use File::Temp ();
use Utils qw/ start_process build_binary_dir status wait_port_connectable setup_basic_slime_cluster require_files_equal kill_wait_for /;

status "Starting git-annex integration test. Versions:";
print STDERR "\n";
system "go version" and die;
print STDERR "\n";
system "git show --oneline -s HEAD" and die;
print STDERR "\n";
system "git version" and die;
print STDERR "\n";
system "git annex version" and die;
print STDERR "\n";
system "uname -a" and die;
print STDERR "\n";

my $binaries = build_binary_dir;

my ($config, $slime_dir) = setup_basic_slime_cluster;

status "Initializing git repo";
my $repo = File::Temp->newdir;
system "git init \Q$repo" and die;
system "cd \Q$repo\E && git annex init" and die;

status "Adding slime remote";
system "cd \Q$repo\E && git annex initremote slime type=external externaltype=slime \Qbaseurl=http://$config->{proxy_listen}/data/\E encryption=none chunk=5000" and die;

status "Adding crappy files to git-annex";
for my $i ( 0 .. 3 ) {
    open my $sf, ">", "$repo/data-$i" or die;
    print $sf join "", map chr rand 256, 1..5555 for 1..5;
    close $sf;
    system "cd \Q$repo\E && git annex add \Qdata-$i\E" and die;
}

system "cd \Q$repo\E && git commit -m 'add crappy files'" and die;

status "Copying files to slime";
system "cd \Q$repo\E && git annex copy --to slime" and die;
system "cd \Q$repo\E && git annex fsck --from slime" and die;

status "Dropping from slime";
system "cd \Q$repo\E && git annex drop --from slime" and die;
system "cd \Q$repo\E && git annex fsck --from slime" and die;

status "Running git annex testremote";
system "cd \Q$repo\E && git annex testremote --fast slime" and die;

status "Stopping slime";
kill_wait_for $_ for @{$config}{"proxy_pid", "chunk_pid"};

status "Passed!";
