#!/bin/sh

glock save -n git.encryptio.com/slime > .glockfile-tmp
diff .glockfile-tmp ../GLOCKFILE || {
    rm .glockfile-tmp
    echo >&2 "GLOCKFILE not up to date"
    exit 1
}
rm .glockfile-tmp
exit 0
