#!/usr/bin/perl
use warnings;
use strict;

use FindBin;

chdir $FindBin::Bin;

my $failed = 0;

opendir my $dh, "." or die;
my @tests =
    sort
    grep { -x $_ and -f $_ }
    grep { !/^\./ }
    grep { $_ ne "run_all" }
    readdir $dh;
closedir $dh;

for my $test ( @tests ) {
    print "===== Running $test =====\n";
    if ( system "\Q./$test\E" ) {
        $failed++;
    }
}

if ( $failed > 0 ) {
    print "FAILED $failed TESTS\n";
} else {
    print "ALL TESTS PASSED\n";
}
exit $failed;
