language: go

go_import_path: github.com/encryptio/slime

addons:
    postgresql: "9.3"

script:
    - git config --global user.name "Travis CI Worker"
    - go get github.com/robfig/glock
    - glock sync github.com/encryptio/slime
    - "(cd /tmp && curl -s https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz | tar -xzf -); export PATH=\"$PATH:/tmp/git-annex.linux\""
    - test/run_all

go:
    - 1.5
    - 1.5.1
    - tip

os:
    - linux
